// This file was generated by counterfeiter
package clientfakes

import (
	"io"
	"sync"

	"github.com/DennisDenuto/uber-sdk/client"
)

type FakeClient struct {
	GetStub        func(url string, queryParams map[string]string) (io.Reader, error)
	getMutex       sync.RWMutex
	getArgsForCall []struct {
		url         string
		queryParams map[string]string
	}
	getReturns struct {
		result1 io.Reader
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeClient) Get(url string, queryParams map[string]string) (io.Reader, error) {
	fake.getMutex.Lock()
	fake.getArgsForCall = append(fake.getArgsForCall, struct {
		url         string
		queryParams map[string]string
	}{url, queryParams})
	fake.recordInvocation("Get", []interface{}{url, queryParams})
	fake.getMutex.Unlock()
	if fake.GetStub != nil {
		return fake.GetStub(url, queryParams)
	} else {
		return fake.getReturns.result1, fake.getReturns.result2
	}
}

func (fake *FakeClient) GetCallCount() int {
	fake.getMutex.RLock()
	defer fake.getMutex.RUnlock()
	return len(fake.getArgsForCall)
}

func (fake *FakeClient) GetArgsForCall(i int) (string, map[string]string) {
	fake.getMutex.RLock()
	defer fake.getMutex.RUnlock()
	return fake.getArgsForCall[i].url, fake.getArgsForCall[i].queryParams
}

func (fake *FakeClient) GetReturns(result1 io.Reader, result2 error) {
	fake.GetStub = nil
	fake.getReturns = struct {
		result1 io.Reader
		result2 error
	}{result1, result2}
}

func (fake *FakeClient) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.getMutex.RLock()
	defer fake.getMutex.RUnlock()
	return fake.invocations
}

func (fake *FakeClient) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ client.Client = new(FakeClient)
